export interface AdditionalHoursModalProps {
    open: boolean;
    setOpen: (isOpen: boolean) => void;
    providerName: string;
    showBreakOne: boolean;
    showBreakTwo: boolean;
    showBreakThree: boolean;
    showAddBreakButton: boolean;
    sunday: {selected: boolean, disabled: boolean};
    monday: {selected: boolean, disabled: boolean};
    tuesday: {selected: boolean, disabled: boolean};
    wednesday: {selected: boolean, disabled: boolean};
    thursday: {selected: boolean, disabled: boolean};
    friday: {selected: boolean, disabled: boolean};
    saturday: {selected: boolean, disabled: boolean};
    startWorking: string;
    endWorking: string;
    setStartWorking: (startHour: string) => void;
    setEndWorking: (endHour: string) => void;
    setSunday: any;
    setMonday: any;
    setTuesday: any;
    setWednesday: any;
    setThursday: any;
    setFriday: any;
    setSaturday: any;
    startBreakOne: string;
    endBreakOne: string;
    startBreakTwo: string;
    endBreakTwo: string;
    startBreakThree: string;
    endBreakThree: string;
    setStartBreakOne: (startBreak: string) => void;
    setEndBreakOne: (startBreak: string) => void;
    setStartBreakTwo: (startBreak: string) => void;
    setEndBreakTwo: (startBreak: string) => void;
    setStartBreakThree: (startBreak: string) => void;
    setEndBreakThree: (startBreak: string) => void;
    handleAddBreak: () => void;
    handleRemoveBreak: (breakNumber: number) => void;
    handleSaveDaysAndHours: () => void;
  }